export class HouseData {
    public id: number;
    public propZpId: string;
    public propArea: number;
    public propBaths: number;
    public propBeds: number;
    public address: string;
    public detailUrl: string;
    public homeZpId: number;
    public bathrooms: number;
    public bedrooms : number;
    public city: string;
    public country: string;
    public dateSold: Date;
    public daysOnZillow: number;
    public homeStatus: string;
    public homeStatusForHDP: string;
    public homeType: string;
    public isPreforclosureAuction: boolean;
    public latitude: number;
    public livingArea: number;
    public longitude: number;
    public lotAreaUnit: string;
    public lotArea: number;
    public price: number;
    public priceForHDP: number;
    public rentZestimate: number;
    public state: string;
    public taxAssessedValue: number;
    public zestimate: number;
    public zipCode: string;
    public imgSrc: string;
    public listingType: string;
    public priceText: string;
    public priceLabel: string;
    public streeViewMetadataUrl: string;
    public streeViewUrl: string;
}